### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by MaoShultz** [VKCOM/lighthouse#1]
How to use authorization?

**Comment by alexey-milovidov** [comment]
Confirmed, I cannot connect with username and password.
Neither with

```
http://readonly:qwerty@127.0.0.1:8123/
```
or

```
http://127.0.0.1:8123/?user=readonly&password=qwerty
```

In the latter case, the UI sends request to the wrong URL:
```
http://127.0.0.1:8123/?user=readonly&password=qwerty/?add_http_cors_header=1&log_queries=1&output_format_json_quote_64bit_integers=1&database=&result_overflow_mode=throw&readonly=1
```

PS. Thank you for opensourcing. The interface is really clean and fast!

**Comment by YuriyNasretdinov** [comment]
Yeah, if for some reason http://readonly:qwerty@127.0.0.1:8123/ does not work then auth is not supported at the moment :). I will fix that in near future. Thank you for your report!

> PS. Thank you for opensourcing. The interface is really clean and fast!

Thank you, Alexey :).

**Comment by duckhawk** [comment]
Hello.
Is there some news about auth? Or, there is no hope?

**Comment by YuriyNasretdinov** [comment]
> Hello.
> Is there some news about auth? Or, there is no hope?

There is hope, actually :). I have just added initial (a bit hacky) support for authorization — you can now just add "/?user=XXX" to URL and you will be asked for password. If you provide URL like "/?user=XXX&password=YYY", then it will just connect without prompting you anything.

**Comment by YuriyNasretdinov** [comment]
You can now choose to use basic auth if you really want to as well.
